libmslc_srcs = files(
    'abort_exit.c',
    'ansi_files.c',
    'ansi_fp.c',
    'arith.c',
    'buffer_io.c',
    'common_float_tables.c',
    'critical_regions.ppc_eabi.c',
    'ctype.c',
    'direct_io.c',
    'e_asin.c',
    'e_atan2.c',
    'e_pow.c',
    'errno.c',
    'float.c',
    'fminmaxdim.c',
    'hyperbolicsf.c',
    'inverse_trig.c',
    'locale.c',
    'math_inlines.c',
    'mbstring.c',
    'mem.c',
    'mem_funcs.c',
    'misc_io.c',
    'printf.c',
    'rand.c',
    's_atan.c',
    's_copysign.c',
    's_frexp.c',
    's_ldexp.c',
    'scanf.c',
    'string.c',
    'strtold.c',
    'strtoul.c',
    'trigf.c',
    'uart_console_io.c',
    'w_atan2.c',
    'w_pow.c',
    'wchar_io.c'
)

libmslc = library('MSL_C',
    include_directories: libporpoise_includes,
    pic: false,
    sources: [libmslc_srcs],
    native: false
)

libporpoise_libs += libmslc
