name: build_linux

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build_linux:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Install Software
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends fuse git python3 wget zip

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Create build container image
        run: ./drun.sh echo done

      - name: Build (Linux)
        run: ./drun.sh ./standalone/scripts/ci_build_linux.sh
